template = "https://github.com/giellalt/template-lang-und"
rev_id = 304
template_sha = "6db72d2e1012558dae41ff0c67944d6ae89b182a"

[replacements]
__GLOTTOLOG_ID__ = "west2618"
__REPO__ = "lang-iku"
__UND2C__ = "iu"
__UNDEFINED__ = "Inuktitut"
__UND__ = "iku"
