template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "2ae3f964876faa6636309f7d609478512097ebd0"

[replacements]
__GLOTTOLOG_ID__ = "west2618"
__REPO__ = "lang-iku"
__UND2C__ = "iu"
__UNDEFINED__ = "Inuktitut"
__UND__ = "iku"
