template = "https://github.com/giellalt/template-lang-und"
rev_id = 286
template_sha = "f08cd05b163db5f27bd203f19e51ee67c3266676"

[replacements]
__GLOTTOLOG_ID__ = "west2618"
__REPO__ = "lang-iku"
__UND2C__ = "iu"
__UNDEFINED__ = "Inuktitut"
__UND__ = "iku"
