[package]
name = "iku"
human_name = "Inuktitut"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.iku]
filename = "iu-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-iku"
platform = "windows"
uuid = "23C1A974-7889-4AD4-BE09-F89AB1F2E210"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.iu"
package = "speller-iku"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-iku-mso"
platform = "windows"
uuid = "AA091315-7297-4EB2-89F1-6AB5069556D8"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-iku"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
